apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
spec:
  containers:
    - name: app
      image: dolsam77/counter
      env: # DB 에 접근하기 위한 환경변수
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis